function handleHRVanalysis()
global TD_Tab TimeDomain_Calculate R_pos fs save_HRV tab1 caseName ECG_data
global HR NN_mean stdnn sdsd rmssd R50 R20 pR50 pR20 T1 FD_Tab Pxx F 
global Frequency_Calculate NA_Tab AA_Tab PP_Tab Complexity_Calculate
global C_bin C_ter KC_bin Nonlinear_Calculate Poincare_Calculate
global SD1 SD2 SD12 aVLF aLF aHF nLF nHF lfhf px6 edit_boxes 
global alpha beta alpha1 beta1 alpha2 beta2 n F_n 
global AE SE px1 n1_edit n2_edit brk_pt_edit m_edit r_edit

HR = NaN; NN_mean = NaN; stdnn = NaN; sdsd = NaN; rmssd = NaN; R50 = NaN; R20 = NaN; pR50 = NaN; pR20 = NaN; 
aVLF = NaN; aLF = NaN; aHF = NaN; nLF = NaN; nHF = NaN; lfhf = NaN; AE = NaN; SE = NaN; alpha = NaN; 
beta = NaN; alpha1 = NaN; beta1 = NaN; alpha2 = NaN; beta2 = NaN; C_bin = NaN; C_ter = NaN; KC_bin = NaN; 
SD1 = NaN; SD2 = NaN; SD12 = NaN;
TimeDomain_Calculate = uicontrol('Parent',TD_Tab,'style', 'pushbutton',...
    'string', 'Calculate',...
    'units', 'normalized',...
    'position', [0.23 0.04 0.2 0.05],...
    'Enable','off','Callback', @Time_Domain);
Frequency_Calculate = uicontrol('Parent',FD_Tab,'style', 'pushbutton',...
                    'string', 'Calculate',...
                    'units', 'normalized',...
                    'position', [0.23 0.04 0.2 0.05],...
                    'Enable','off','Callback', @Frequency_Domain);
Nonlinear_Calculate = uicontrol('Parent',NA_Tab,'style', 'pushbutton',...
                    'string', 'Calculate',...
                    'units', 'normalized',...
                    'position', [0.23 0.04 0.2 0.05],...
                    'Enable','off','Callback', @Nonlinear);
Complexity_Calculate = uicontrol('Parent',AA_Tab,'style', 'pushbutton',...
                    'string', 'Calculate',...
                    'units', 'normalized',...
                    'position', [0.23 0.04 0.2 0.05],...
                    'Enable','off','Callback', @Complexity);
Poincare_Calculate = uicontrol('Parent',PP_Tab,'style', 'pushbutton',...
                    'string', 'Calculate',...
                    'units', 'normalized',...
                    'position', [0.23 0.04 0.2 0.05],...
                    'Enable','off','Callback', @Poincare);

Parameter_text_AA = uicontrol('Parent',PP_Tab,'style', 'text',...
    'string','Parameter','FontSize', 10,'FontWeight', 'bold',...
    'units', 'normalized',...
    'position', [0.078 0.9 0.15 0.05]);
Value_text_AA = uicontrol('Parent',PP_Tab,'style', 'text',...
    'string','Value','FontSize', 10,'FontWeight', 'bold',...
    'units', 'normalized',...
    'position', [0.25 0.9 0.15 0.05]);
Unit_tab_text_AA = uicontrol('Parent',PP_Tab,'style', 'text',...
    'string','Unit','FontSize', 10,'FontWeight', 'bold',...
    'units', 'normalized',...
    'position', [0.4 0.9 0.12 0.05]);
px15 = axes('Parent', PP_Tab, 'Position', [0.11 0.1 0.1 0.78], 'Visible', 'off');
px15.Toolbar.Visible = 'off';
text('Parent', px15, 'Position', [0.5, 0.7], 'String', 'SD1/SD2', ...
    'FontSize', 10, 'HorizontalAlignment', 'center', 'Interpreter', 'tex');
text('Parent', px15, 'Position', [0.5, 0.83], 'String', 'SD2', ...
    'FontSize', 10, 'HorizontalAlignment', 'center', 'Interpreter', 'tex');
text('Parent', px15, 'Position', [0.5, 0.96], 'String', 'SD1', ...
    'FontSize', 10, 'HorizontalAlignment', 'center', 'Interpreter', 'tex');
px14 = axes('Parent', PP_Tab, 'Position', [0.4105 0.1 0.1 0.78], 'Visible', 'off');
px14.Toolbar.Visible = 'off';
text('Parent', px14, 'Position', [0.5, 0.7], 'String', '-', ...
    'FontSize', 10, 'HorizontalAlignment', 'center', 'Interpreter', 'tex');
text('Parent', px14, 'Position', [0.5, 0.83], 'String', 'ms', ...
    'FontSize', 10, 'HorizontalAlignment', 'center', 'Interpreter', 'tex');
text('Parent', px14, 'Position', [0.5, 0.96], 'String', 'ms', ...
    'FontSize', 10, 'HorizontalAlignment', 'center', 'Interpreter', 'tex');
SD1_value = uicontrol('Parent',PP_Tab,'style', 'edit',...
    'units', 'normalized',...
    'position',[0.28 0.82 0.1 0.05], ...
    'Enable','off','Callback',@string_to_num1);
SD2_value = uicontrol('Parent',PP_Tab,'style', 'edit',...
    'units', 'normalized',...
    'position',[0.28 0.72 0.1 0.05], ...
    'Enable','off','Callback',@string_to_num1);
SD1SD2_value = uicontrol('Parent',PP_Tab,'style', 'edit',...
    'units', 'normalized',...
    'position',[0.28 0.62 0.1 0.05], ...
    'Enable','off','Callback',@string_to_num1);

Parameter_text_AA = uicontrol('Parent',AA_Tab,'style', 'text',...
    'string','Parameter','FontSize', 10,'FontWeight', 'bold',...
    'units', 'normalized',...
    'position', [0.078 0.9 0.15 0.05]);
Value_text_AA = uicontrol('Parent',AA_Tab,'style', 'text',...
    'string','Value','FontSize', 10,'FontWeight', 'bold',...
    'units', 'normalized',...
    'position', [0.25 0.9 0.15 0.05]);
Unit_tab_text_AA = uicontrol('Parent',AA_Tab,'style', 'text',...
    'string','Unit','FontSize', 10,'FontWeight', 'bold',...
    'units', 'normalized',...
    'position', [0.4 0.9 0.12 0.05]);

px12 = axes('Parent', AA_Tab, 'Position', [0.11 0.1 0.1 0.78], 'Visible', 'off');
px12.Toolbar.Visible = 'off';
text('Parent', px12, 'Position', [0.5, 0.7], 'String', 'KC (Bin)', ...
    'FontSize', 10, 'HorizontalAlignment', 'center', 'Interpreter', 'tex');
text('Parent', px12, 'Position', [0.5, 0.83], 'String', 'LZ Comp (Ter)', ...
    'FontSize', 10, 'HorizontalAlignment', 'center', 'Interpreter', 'tex');
text('Parent', px12, 'Position', [0.5, 0.96], 'String', 'LZ Comp (Bin)', ...
    'FontSize', 10, 'HorizontalAlignment', 'center', 'Interpreter', 'tex');
px13 = axes('Parent', AA_Tab, 'Position', [0.4105 0.1 0.1 0.78], 'Visible', 'off');
px13.Toolbar.Visible = 'off';
text('Parent', px13, 'Position', [0.5, 0.7], 'String', '-', ...
    'FontSize', 10, 'HorizontalAlignment', 'center', 'Interpreter', 'tex');
text('Parent', px13, 'Position', [0.5, 0.83], 'String', '-', ...
    'FontSize', 10, 'HorizontalAlignment', 'center', 'Interpreter', 'tex');
text('Parent', px13, 'Position', [0.5, 0.96], 'String', '-', ...
    'FontSize', 10, 'HorizontalAlignment', 'center', 'Interpreter', 'tex');

LZ1_value = uicontrol('Parent',AA_Tab,'style', 'edit',...
    'units', 'normalized',...
    'position',[0.28 0.82 0.1 0.05], ...
    'Enable','off','Callback',@string_to_num1);
LZ2_value = uicontrol('Parent',AA_Tab,'style', 'edit',...
    'units', 'normalized',...
    'position',[0.28 0.72 0.1 0.05], ...
    'Enable','off','Callback',@string_to_num1);
KC_value = uicontrol('Parent',AA_Tab,'style', 'edit',...
    'units', 'normalized',...
    'position',[0.28 0.62 0.1 0.05], ...
    'Enable','off','Callback',@string_to_num1);
Parameter_text_NA = uicontrol('Parent',NA_Tab,'style', 'text',...
    'string','Parameter','FontSize', 10,'FontWeight', 'bold',...
    'units', 'normalized',...
    'position', [0.078 0.9 0.15 0.05]);
Value_text_NA = uicontrol('Parent',NA_Tab,'style', 'text',...
    'string','Value','FontSize', 10,'FontWeight', 'bold',...
    'units', 'normalized',...
    'position', [0.25 0.9 0.15 0.05]);
Unit_tab_text_NA = uicontrol('Parent',NA_Tab,'style', 'text',...
    'string','Unit','FontSize', 10,'FontWeight', 'bold',...
    'units', 'normalized',...
    'position', [0.4 0.9 0.12 0.05]);

px10 = axes('Parent', NA_Tab, 'Position', [0.11 0.1 0.1 0.78], 'Visible', 'off');
px10.Toolbar.Visible = 'off';
text('Parent', px10, 'Position', [0.5, 0.45], 'String', '\alpha2', ...
    'FontSize', 10, 'HorizontalAlignment', 'center', 'Interpreter', 'tex');
text('Parent', px10, 'Position', [0.5, 0.58], 'String', '\alpha1', ...
    'FontSize', 10, 'HorizontalAlignment', 'center', 'Interpreter', 'tex');
text('Parent', px10, 'Position', [0.5, 0.7], 'String', '\alpha ', ...
    'FontSize', 10, 'HorizontalAlignment', 'center', 'Interpreter', 'tex');
text('Parent', px10, 'Position', [0.5, 0.83], 'String', 'SampEn', ...
    'FontSize', 10, 'HorizontalAlignment', 'center', 'Interpreter', 'tex');
text('Parent', px10, 'Position', [0.5, 0.96], 'String', 'ApEn', ...
    'FontSize', 10, 'HorizontalAlignment', 'center', 'Interpreter', 'tex');

px11 = axes('Parent', NA_Tab, 'Position', [0.4105 0.1 0.1 0.78], 'Visible', 'off');
px11.Toolbar.Visible = 'off';
text('Parent', px11, 'Position', [0.5, 0.45], 'String', '-', ...
    'FontSize', 10, 'HorizontalAlignment', 'center', 'Interpreter', 'tex');
text('Parent', px11, 'Position', [0.5, 0.58], 'String', '-', ...
    'FontSize', 10, 'HorizontalAlignment', 'center', 'Interpreter', 'tex');
text('Parent', px11, 'Position', [0.5, 0.7], 'String', '-', ...
    'FontSize', 10, 'HorizontalAlignment', 'center', 'Interpreter', 'tex');
text('Parent', px11, 'Position', [0.5, 0.83], 'String', '-', ...
    'FontSize', 10, 'HorizontalAlignment', 'center', 'Interpreter', 'tex');
text('Parent', px11, 'Position', [0.5, 0.96], 'String', '-', ...
    'FontSize', 10, 'HorizontalAlignment', 'center', 'Interpreter', 'tex');

AE_value = uicontrol('Parent',NA_Tab,'style', 'edit',...
    'units', 'normalized',...
    'position',[0.28 0.82 0.1 0.05], ...
    'Enable','off','Callback',@string_to_num1);
SE_value = uicontrol('Parent',NA_Tab,'style', 'edit',...
    'units', 'normalized',...
    'position',[0.28 0.72 0.1 0.05], ...
    'Enable','off','Callback',@string_to_num1);
alpha_value = uicontrol('Parent',NA_Tab,'style', 'edit',...
    'units', 'normalized',...
    'position',[0.28 0.62 0.1 0.05], ...
    'Enable','off','Callback',@string_to_num1);

alpha1_value = uicontrol('Parent',NA_Tab,'style', 'edit',...clear R
    'units', 'normalized',...
    'position',[0.28 0.52 0.1 0.05], ...
    'Enable','off','Callback',@string_to_num1);
alpha2_value = uicontrol('Parent',NA_Tab,'style', 'edit',...
    'units', 'normalized',...
    'position',[0.28 0.42 0.1 0.05], ...
    'Enable','off','Callback',@string_to_num1);

n1_edit = uicontrol('Parent',NA_Tab,'style', 'edit',...
    'units', 'normalized',...
    'position',[0.55 0.63 0.1 0.05]);
n2_edit = uicontrol('Parent',NA_Tab,'style', 'edit',...
    'units', 'normalized',...
    'position',[0.85 0.63 0.1 0.05]);
brk_pt_edit = uicontrol('Parent',NA_Tab,'style', 'edit',...
    'units', 'normalized',...
    'position',[0.7 0.63 0.1 0.05]);

m_edit = uicontrol('Parent',NA_Tab,'style', 'edit',...
    'units', 'normalized',...
    'position',[0.62 0.78 0.1 0.05]);
r_edit = uicontrol('Parent',NA_Tab,'style', 'edit',...
    'units', 'normalized',...
    'position',[0.8 0.78 0.1 0.05]);



px16 = axes('Parent', NA_Tab, 'Position', [0.55 0.56 0.4 0.4], 'Visible', 'off');
text('Parent', px16, 'Position', [0.31, 0.75], 'String', 'for ApEn and SampEn', ...
    'FontSize', 10, 'HorizontalAlignment', 'center', 'Interpreter', 'tex');
text('Parent', px16, 'Position', [0.09, 0.63], 'String', 'm', ...
    'FontSize', 10, 'HorizontalAlignment', 'center', 'Interpreter', 'tex');
text('Parent', px16, 'Position', [0.54, 0.63], 'String', 'r', ...
    'FontSize', 10, 'HorizontalAlignment', 'center', 'Interpreter', 'tex');
text('Parent', px16, 'Position', [0.09, 0.12], 'String', 'n1', ...
    'FontSize', 10,  'Interpreter', 'tex');
text('Parent', px16, 'Position', [0.84 0.12], 'String', 'n2', ...
    'FontSize', 10, 'Interpreter', 'tex');
text('Parent', px16, 'Position', [0.46, 0.12], 'String', 'bkp', ...
    'FontSize', 10, 'Interpreter', 'tex');
text('Parent', px16, 'Position', [0.41, 0.47], 'String', 'for \alpha1: n1 to breakpoint (bkp)', ...
    'FontSize', 10, 'HorizontalAlignment', 'center', 'Interpreter', 'tex');
text('Parent', px16, 'Position', [0.32, 0.37], 'String', 'for \alpha2: breakpoint to n2', ...
    'FontSize', 10, 'HorizontalAlignment', 'center', 'Interpreter', 'tex');

Parameter_text_NA = uicontrol('Parent',NA_Tab,'style', 'text',...
    'string','Parameter','FontSize', 10,'FontWeight', 'bold',...
    'units', 'normalized',...
    'position', [0.078 0.9 0.15 0.05]);
Value_text_NA = uicontrol('Parent',NA_Tab,'style', 'text',...
    'string','Value','FontSize', 10,'FontWeight', 'bold',...
    'units', 'normalized',...
    'position', [0.25 0.9 0.15 0.05]);
Unit_tab_text_NA = uicontrol('Parent',NA_Tab,'style', 'text',...
    'string','Unit','FontSize', 10,'FontWeight', 'bold',...
    'units', 'normalized',...
    'position', [0.4 0.9 0.12 0.05]);

Parameter_text_FD = uicontrol('Parent',FD_Tab,'style', 'text',...
    'string','Parameter','FontSize', 10,'FontWeight', 'bold',...
    'units', 'normalized',...
    'position', [0.078 0.9 0.15 0.05]);
Value_text_FD = uicontrol('Parent',FD_Tab,'style', 'text',...
    'string','Value','FontSize', 10,'FontWeight', 'bold',...
    'units', 'normalized',...
    'position', [0.25 0.9 0.15 0.05]);
Unit_tab_text_FD = uicontrol('Parent',FD_Tab,'style', 'text',...
    'string','Unit','FontSize', 10,'FontWeight', 'bold',...
    'units', 'normalized',...
    'position', [0.4 0.9 0.12 0.05]);
px = axes('Parent', FD_Tab, 'Position', [0.4105 0.3 0.1 0.58], 'Visible', 'off');
px.Toolbar.Visible = 'off';
% Add text to the axes with LaTeX interpreter
text('Parent', px, 'Position', [0.5, 0.09], 'String', '-', ...
    'FontSize', 10, 'HorizontalAlignment', 'center', 'Interpreter', 'tex');
text('Parent', px, 'Position', [0.5, 0.26], 'String', 'n.u.', ...
    'FontSize', 10, 'HorizontalAlignment', 'center', 'Interpreter', 'tex');
text('Parent', px, 'Position', [0.5, 0.43], 'String', 'n.u.', ...
    'FontSize', 10, 'HorizontalAlignment', 'center', 'Interpreter', 'tex');
text('Parent', px, 'Position', [0.5, 0.61], 'String', 'ms^{2}', ...
    'FontSize', 10, 'HorizontalAlignment', 'center', 'Interpreter', 'tex');
text('Parent', px, 'Position', [0.5, 0.79], 'String', 'ms^{2}', ...
    'FontSize', 10, 'HorizontalAlignment', 'center', 'Interpreter', 'tex');
text('Parent', px, 'Position', [0.5, 0.96], 'String', 'ms^{2}', ...
    'FontSize', 10, 'HorizontalAlignment', 'center', 'Interpreter', 'tex');
px7 = axes('Parent', FD_Tab, 'Position', [0.09 0.3 0.1 0.58], 'Visible', 'off');
px7.Toolbar.Visible = 'off';
text('Parent', px7, 'Position', [0.5, 0.09], 'String', 'LF/HF', ...
    'FontSize', 10, 'HorizontalAlignment', 'center', 'Interpreter', 'tex');
text('Parent', px7, 'Position', [0.5, 0.26], 'String', 'nHF', ...
    'FontSize', 10, 'HorizontalAlignment', 'center', 'Interpreter', 'tex');
text('Parent', px7, 'Position', [0.5, 0.43], 'String', 'nLF.', ...
    'FontSize', 10, 'HorizontalAlignment', 'center', 'Interpreter', 'tex');
text('Parent', px7, 'Position', [0.5, 0.61], 'String', 'aHF', ...
    'FontSize', 10, 'HorizontalAlignment', 'center', 'Interpreter', 'tex');
text('Parent', px7, 'Position', [0.5, 0.79], 'String', 'aLF', ...
    'FontSize', 10, 'HorizontalAlignment', 'center', 'Interpreter', 'tex');
text('Parent', px7, 'Position', [0.5, 0.96], 'String', 'aVLF', ...
    'FontSize', 10, 'HorizontalAlignment', 'center', 'Interpreter', 'tex');

aVLF_value = uicontrol('Parent',FD_Tab,'style', 'edit',...
    'units', 'normalized',...
    'position',[0.28 0.82 0.1 0.05], ...
    'Enable','off','Callback',@string_to_num1);
aLF_value = uicontrol('Parent',FD_Tab,'style', 'edit',...
    'units', 'normalized',...
    'position',[0.28 0.72 0.1 0.05], ...
    'Enable','off','Callback',@string_to_num1);
aHF_value = uicontrol('Parent',FD_Tab,'style', 'edit',...
    'units', 'normalized',...
    'position',[0.28 0.62 0.1 0.05], ...
    'Enable','off','Callback',@string_to_num1);
nLF_value = uicontrol('Parent',FD_Tab,'style', 'edit',...
    'units', 'normalized',...
    'position',[0.28 0.52 0.1 0.05], ...
    'Enable','off','Callback',@string_to_num1);
nHF_value = uicontrol('Parent',FD_Tab,'style', 'edit',...clear R
    'units', 'normalized',...
    'position',[0.28 0.42 0.1 0.05], ...
    'Enable','off','Callback',@string_to_num1);
LFHF_value = uicontrol('Parent',FD_Tab,'style', 'edit',...
    'units', 'normalized',...
    'position',[0.28 0.32 0.1 0.05], ...
    'Enable','off','Callback',@string_to_num1);





Parameter_text_TD = uicontrol('Parent',TD_Tab,'style', 'text',...
    'string','Parameter','FontSize', 10,'FontWeight', 'bold',...
    'units', 'normalized',...
    'position', [0.078 0.9 0.15 0.05]);
Value_text_TD = uicontrol('Parent',TD_Tab,'style', 'text',...
    'string','Value','FontSize', 10,'FontWeight', 'bold',...
    'units', 'normalized',...
    'position', [0.25 0.9 0.15 0.05]);
Unit_tab_text_TD = uicontrol('Parent',TD_Tab,'style', 'text',...
    'string','Unit','FontSize', 10,'FontWeight', 'bold',...
    'units', 'normalized',...
    'position', [0.4 0.9 0.12 0.05]);
px8 = axes('Parent', TD_Tab, 'Position', [0.11 0.1 0.1 0.78], 'Visible', 'off');
px8.Toolbar.Visible = 'off';
text('Parent', px8, 'Position', [0.5, 0.07], 'String', 'pNN20', ...
    'FontSize', 10, 'HorizontalAlignment', 'center', 'Interpreter', 'tex');
text('Parent', px8, 'Position', [0.5, 0.2], 'String', 'NN20', ...
    'FontSize', 10, 'HorizontalAlignment', 'center', 'Interpreter', 'tex');
text('Parent', px8, 'Position', [0.5, 0.32], 'String', 'pNN50', ...
    'FontSize', 10, 'HorizontalAlignment', 'center', 'Interpreter', 'tex');
text('Parent', px8, 'Position', [0.5, 0.45], 'String', 'NN50', ...
    'FontSize', 10, 'HorizontalAlignment', 'center', 'Interpreter', 'tex');
text('Parent', px8, 'Position', [0.5, 0.58], 'String', 'RMSDD', ...
    'FontSize', 10, 'HorizontalAlignment', 'center', 'Interpreter', 'tex');
text('Parent', px8, 'Position', [0.5, 0.7], 'String', 'SDSD', ...
    'FontSize', 10, 'HorizontalAlignment', 'center', 'Interpreter', 'tex');
text('Parent', px8, 'Position', [0.5, 0.83], 'String', 'STDNN', ...
    'FontSize', 10, 'HorizontalAlignment', 'center', 'Interpreter', 'tex');
text('Parent', px8, 'Position', [0.5, 0.96], 'String', 'NNmean', ...
    'FontSize', 10, 'HorizontalAlignment', 'center', 'Interpreter', 'tex');
px9 = axes('Parent', TD_Tab, 'Position', [0.4105 0.1 0.1 0.78], 'Visible', 'off');
px9.Toolbar.Visible = 'off';
text('Parent', px9, 'Position', [0.5, 0.07], 'String', '%', ...
    'FontSize', 10, 'HorizontalAlignment', 'center', 'Interpreter', 'tex');
text('Parent', px9, 'Position', [0.5, 0.2], 'String', 'count', ...
    'FontSize', 10, 'HorizontalAlignment', 'center', 'Interpreter', 'tex');
text('Parent', px9, 'Position', [0.5, 0.32], 'String', '%', ...
    'FontSize', 10, 'HorizontalAlignment', 'center', 'Interpreter', 'tex');
text('Parent', px9, 'Position', [0.5, 0.45], 'String', 'count', ...
    'FontSize', 10, 'HorizontalAlignment', 'center', 'Interpreter', 'tex');
text('Parent', px9, 'Position', [0.5, 0.58], 'String', 'ms', ...
    'FontSize', 10, 'HorizontalAlignment', 'center', 'Interpreter', 'tex');
text('Parent', px9, 'Position', [0.5, 0.7], 'String', 'ms', ...
    'FontSize', 10, 'HorizontalAlignment', 'center', 'Interpreter', 'tex');
text('Parent', px9, 'Position', [0.5, 0.83], 'String', 'ms', ...
    'FontSize', 10, 'HorizontalAlignment', 'center', 'Interpreter', 'tex');
text('Parent', px9, 'Position', [0.5, 0.96], 'String', 'ms', ...
    'FontSize', 10, 'HorizontalAlignment', 'center', 'Interpreter', 'tex');
NNmean_value = uicontrol('Parent',TD_Tab,'style', 'edit',...
    'units', 'normalized',...
    'position',[0.28 0.82 0.1 0.05], ...
    'Enable','off','Callback',@string_to_num1);
STDNN_value = uicontrol('Parent',TD_Tab,'style', 'edit',...
    'units', 'normalized',...
    'position',[0.28 0.72 0.1 0.05], ...
    'Enable','off','Callback',@string_to_num1);
SDSD_value = uicontrol('Parent',TD_Tab,'style', 'edit',...
    'units', 'normalized',...
    'position',[0.28 0.62 0.1 0.05], ...
    'Enable','off','Callback',@string_to_num1);
RMSDD_value = uicontrol('Parent',TD_Tab,'style', 'edit',...
    'units', 'normalized',...
    'position',[0.28 0.52 0.1 0.05], ...
    'Enable','off','Callback',@string_to_num1);
NN50_value = uicontrol('Parent',TD_Tab,'style', 'edit',...clear R
    'units', 'normalized',...
    'position',[0.28 0.42 0.1 0.05], ...
    'Enable','off','Callback',@string_to_num1);
pNN50_value = uicontrol('Parent',TD_Tab,'style', 'edit',...
    'units', 'normalized',...
    'position',[0.28 0.32 0.1 0.05], ...
    'Enable','off','Callback',@string_to_num1);
NN20_value = uicontrol('Parent',TD_Tab,'style', 'edit',...
    'units', 'normalized',...
    'position',[0.28 0.22 0.1 0.05], ...
    'Enable','off','Callback',@string_to_num1);
pNN20_value = uicontrol('Parent',TD_Tab,'style', 'edit',...
    'units', 'normalized',...
    'position',[0.28 0.12 0.1 0.05], ...
    'Enable','off','Callback',@string_to_num1);
save_HRV = uicontrol('Parent',tab1,'style', 'pushbutton',...
    'string', 'Save HRV Data',...
    'units', 'normalized',...
    'position', [0.77 0.55 0.092 0.19],...
    'Enable','off','Callback', @saveHRVdata);
save_data = uicontrol('Parent',tab1,'style', 'pushbutton',...
    'string', 'Save ECG and R peaks',...
    'units', 'normalized',...
    'position', [0.77 0.25 0.092 0.19],...
    'Enable','off','Callback', @savedata);
edit_boxes =[NNmean_value STDNN_value SDSD_value RMSDD_value...
    NN50_value pNN50_value NN20_value pNN20_value aVLF_value...
    aLF_value aHF_value nLF_value nHF_value LFHF_value...
    alpha_value AE_value SE_value alpha1_value alpha2_value...
    SD1_value SD2_value...
    SD1SD2_value LZ1_value LZ2_value KC_value];

    function Poincare(object, event)
        RR_intervals=diff(R_pos);
        [SD1,SD2,SD12]=HRV_Poincare(RR_intervals,1);
        set(SD1_value,'string',SD1);
        set(SD2_value,'string',SD2);
        set(SD1SD2_value,'string',SD12);
        set(SD1_value,'Enable','on');
        set(SD2_value,'Enable','on');
        set(SD1SD2_value,'Enable','on');
        set(save_HRV,'Enable','on');
        set(save_data,'Enable','on');

    end

    function Time_Domain(object, event)
        RR_intervals=diff(R_pos);
        ECG_Signal{1,1}=ECG_data;
        Rpeak_Locs{1,1}=R_pos';
        T1=table(ECG_Signal,Rpeak_Locs);
        [HR, NN_mean,stdnn,sdsd,rmssd,R50,R20,pR50,pR20]=HRV_TimeDomain(RR_intervals,fs);
        set(NNmean_value,'string',NN_mean);
        set(STDNN_value,'string',stdnn);
        set(SDSD_value,'string',sdsd);
        set(RMSDD_value,'string',rmssd);
        set(NN50_value,'string',R50);
        set(pNN50_value,'string',pR50);
        set(NN20_value,'string',R20);
        set(pNN20_value,'string',pR20);
        set(NNmean_value,'Enable','on');
        set(STDNN_value,'Enable','on');
        set(SDSD_value,'Enable','on');
        set(RMSDD_value,'Enable','on');
        set(NN50_value,'Enable','on');
        set(pNN50_value,'Enable','on');
        set(NN20_value,'Enable','on');
        set(pNN20_value,'Enable','on');
        set(save_HRV,'Enable','on');
        set(save_data,'Enable','on');
    end

    function saveHRVdata(object, event)
        excelFileName = 'HRV_Analysis.xlsx'; % You can customize this file name
        % Write to Excel file
        startingFolder = pwd;
        [file, path]= uiputfile('*.xlsx', 'Save File As');
        if isequal(file, 0) || isequal(path, 0)
            disp('User canceled file saving');
        else
            fullExcelFileName = fullfile(path, file);
            T=table(HR, NN_mean,stdnn,sdsd,rmssd,R50,R20,pR50,pR20,aVLF,...
                aLF, aHF, nLF, nHF, lfhf,AE, SE, alpha,alpha1,alpha2,...
                C_bin,C_ter,KC_bin,SD1,SD2,SD12);
            % Specify the Excel file name to save
            %T=table(TimeDomain_name,TimeDomain_parameters,'VariableNames',{'Parameters',caseName});
            writetable(T, fullExcelFileName, 'Sheet', 1);
            msgbox(['Data saved to ' pwd], 'Success');
        end
    end

    function Complexity(object, event)
            RR_intervals=diff(R_pos);
            ECG_Signal{1,1}=ECG_data;
            Rpeak_Locs{1,1}=R_pos';
            T1=table(ECG_Signal,Rpeak_Locs);
            [C_bin,C_ter,KC_bin]=HRV_Complexity(RR_intervals,fs);
            set(LZ1_value,'string',C_bin);
            set(LZ2_value,'string',C_ter);
            set(KC_value,'string',KC_bin);
            set(LZ1_value,'Enable','on');
            set(LZ2_value,'Enable','on');
            set(KC_value,'Enable','on');
            set(save_HRV,'Enable','on');
            set(save_data,'Enable','on');
    end

    function Nonlinear(object, event)
        RR_intervals=diff(R_pos);
        ECG_Signal{1,1}=ECG_data;
        Rpeak_Locs{1,1}=R_pos';
        T1=table(ECG_Signal,Rpeak_Locs);
        if isempty(n1_edit.String)||isempty(n2_edit.String)||isempty(brk_pt_edit.String)
        set(n1_edit,'string',4);
        set(n2_edit, 'string',20)
        set(brk_pt_edit, 'string',11)
        end
        if isempty(m_edit.String)||isempty(r_edit.String)
        set(m_edit,'string',2);
        set(r_edit, 'string',0.2)
        end
%         n1=5;
%         n2=40;
%         bkp=15;
        [alpha,alpha1, alpha2, n, F_n,AE,SE]=HRV_Nonlinear(RR_intervals,str2num(m_edit.String), str2num(r_edit.String),fs,str2num(n1_edit.String),...
            str2num(n2_edit.String),str2num(brk_pt_edit.String),1);
        beta=alpha(2);
        beta1=alpha1(2);
        beta2=alpha1(2);
        alpha=alpha(1);
        alpha1=alpha1(1);
        alpha2=alpha2(1);
        set(AE_value,'string',AE);
        set(SE_value,'string',SE);
        set(alpha_value,'string',alpha);
        set(alpha1_value,'string',alpha1);
        set(alpha2_value,'string',alpha2);
        set(AE_value,'Enable','on');
        set(SE_value,'Enable','on');
        set(alpha_value,'Enable','on');
        set(alpha1_value,'Enable','on');
        set(alpha2_value,'Enable','on');
    end
    function Frequency_Domain(object, event)
        RR_intervals=diff(R_pos);
        ECG_Signal{1,1}=ECG_data;
        Rpeak_Locs{1,1}=R_pos';
        T1=table(ECG_Signal,Rpeak_Locs);
        [aVLF, aLF, aHF, nLF,nHF,lfhf]=HRV_FrequencyDomain(R_pos,RR_intervals,fs);
        
        if exist('px1','var')
        delete(px1)
        end
        px1 = axes('Parent', FD_Tab, 'Position', [0.6 0.35 0.34 0.55], 'Visible', 'on');
        plot(px1,F, Pxx)
        xlabel(px1, 'Frequency (Hz)');
        ylabel(px1, 'PSD (dB/kHz)');
        tb = axtoolbar(px1,{'zoomin','zoomout','rotate','restoreview','pan','datacursor'});
        set(aVLF_value,'string',aVLF);
        set(aLF_value,'string',aLF);
        set(aHF_value,'string',aHF);
        set(nLF_value,'string',nLF);
        set(nHF_value,'string',nHF);
        set(LFHF_value,'string',lfhf);
        set(aVLF_value,'Enable','on');
        set(aLF_value,'Enable','on');
        set(aHF_value,'Enable','on');
        set(nLF_value,'Enable','on');
        set(nHF_value,'Enable','on');
        set(LFHF_value,'Enable','on');
        set(save_HRV,'Enable','on');
        set(save_data,'Enable','on');
    end

    function savedata(object, event)
        startingFolder = pwd; % Or "pwd" or wherever you want.
        defaultFileName = fullfile(startingFolder, '*.*');
        [baseFileName, folder] = uiputfile(defaultFileName, 'T1');
        if baseFileName == 0
            % User clicked the Cancel button.
            return;
        end
        FileName = fullfile(folder, baseFileName);
        save(FileName, 'T1');
        msgbox(['Data saved to ' pwd], 'Success');
    end


end